<?php namespace App\Site\Website;

use App\ServiceManager;
use Phlex\RedFox\Attachment\ThumbnailResponder;
use Phlex\Routing\Router;

/**
 * @domain @ www.@
 */
class Site extends \Phlex\Routing\Site {

	protected function init() {
		parent::init(); // TODO: Change the autogenerated stub
		ServiceManager::bind('HandyResponderDistFolder')->value('/dist/www/');
		ServiceManager::bind('HandyResponderCustomTagNamespace')->value('App.Site.Website.Customtag');
	}

	function route(Router $router) {
		$router->get('/thumbnails/*', ThumbnailResponder::class);
		//$router->addMiddleware(ErrorCatcher::class);
		$router->get('/', Page\Index::class);
	}

}
