#!/usr/bin/env php
<?php
putenv('ROOT='.realpath(__DIR__));
putenv('CONTEXT=cli');
ini_set('error_log', './var/log/app.log');

require __DIR__.'/autoload.php';

if(file_exists(__DIR__.'/config/config.php')) \App\Env::load();

\App\Cli\Application::cli();