<!doctype html>
<html lang="<?php echo $this->lang; ?>">
<head>
<title><?php echo $this->title; ?></title>
<meta charset="utf-8">
<?php $this->writeHeaderExtensions();?>
</head>
<body>
<nav class="main navbar navbar-inverse navbar-static-top" style="margin-bottom:0;">
<div class="container-fluid">
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<div class="navbar-brand" href="#">Phlex</div>
</div>
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<ul class="nav navbar-nav menu">
</ul>
<ul class="nav navbar-nav navbar-right">
<li><a href="/logout">Logout</a></li>
</ul>
</div>
</div>
</nav>
<div class="container-fluid" style="height:calc(100% - 50px);">
<div class="row" style="height: 100%;">
<div class="col-md-6 box-list">
</div>
<div class="col-md-6 box-form">
<div>
</div>
</div>
</div>
</div>
<?php $serverDataJson = json_encode($this->getServerData());?>
<script> var serverData = <?php echo $serverDataJson; ?>; </script>
<?php $this->writeDependencyExtensions();?>
<?php $this->runScript();?>
</body>
</html>
