<?php namespace App\Site\Admin;

use App\ServiceManager;
use Phlex\RedFox\Attachment\ThumbnailResponder;
use Phlex\Routing\Router;

/**
 * @domain admin.@
 */
class Site extends \Phlex\Routing\Site {

	protected function init() {
		parent::init(); // TODO: Change the autogenerated stub
		ServiceManager::bind('HandyResponderDistFolder')->value('/dist/admin/');
		ServiceManager::bind('HandyResponderCustomTagNamespace')->value('App.Site.Admin.Customtag');
	}

	function route(Router $router) {
		$router->get('/thumbnails/*', ThumbnailResponder::class);
		//$router->addMiddleware(ErrorCatcher::class);

		$router->get('/', Page\Index::class);
		$router->get('/menu', Action\GetMenu::class);

		Form\UserAdminDescriptor::createRoutes($router);
	}
}
