<?php namespace App\Site\Admin;

use App\ServiceManager;
use App\Site\Admin\Middleware\AuthCheck;
use Phlex\ErrorHandling\ErrorDebugCatcher;
use Phlex\ErrorHandling\PageExceptionCacher;
use Phlex\RedFox\Attachment\ThumbnailResponder;
use Phlex\Routing\Router;

/**
 * @domain admin.@
 */
class Site extends \Phlex\Routing\Site {

	protected function init() {
		parent::init(); // TODO: Change the autogenerated stub
		ServiceManager::bind('HandyResponderDistFolder')->value('/dist/admin/');
		ServiceManager::bind('HandyResponderCustomTagNamespace')->value('App.Site.Admin.Customtag');
		ServiceManager::bind('AuthService')->sharedService(\App\Site\Admin\Service\AuthService::class);
	}

	function route(Router $router) {
		//$router->addMiddleware(ErrorDebugCatcher::class);
		//$router->addMiddleware(PageExceptionCacher::class);

		$router->post('/login', Action\AuthAction::class, ['method'=>'login']);
		$router->post('/logout', Action\AuthAction::class, ['method'=>'logout']);

		$router->addMiddleware(AuthCheck::class);

		$router->get('/thumbnails/*', ThumbnailResponder::class);

		$router->post('/get-user-data', Action\GetUserDataAction::class);
		$router->post('/get-subject-data', Action\GetSubjectDataAction::class);
		$router->get(['/get-active-subjects/get/{ids}', '/get-active-subjects|/{search}'], Action\GetActiveSubjects::class);
		$router->get(['/get-active-users/get/{ids}', '/get-active-users|/{search}'], Action\GetActiveUsers::class);

		$router->get('/', Page\Index::class);
		$router->get('/menu', Action\GetMenu::class);

		Form\UserAdminDescriptor::createRoutes($router);
		Form\SubjectAdminDescriptor::createRoutes($router);
		Form\CurriculumAdminDescriptor::createRoutes($router);
		Form\SkillAdminDescriptor::createRoutes($router);
		Form\ProgrammeAdminDescriptor::createRoutes($router);
		Form\AdministratorAdminDescriptor::createRoutes($router);
	}
}
